version: '3'

services:

  myapp-mysql:
    image: jackcooper1245/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=deloitte
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  myapp-main:
    image: thisone
    restart: on-failure
    depends_on:
      - myapp-mysql
    network_mode: host
    ports:
      - 8080:80
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=deloitte
      - DATABASE_PORT=3306
